name = "prng"
version = "4.0.2"
description = "A Pure Random Number Generator"

licences = ["Apache-2.0"]
repository = { type = "github", user = "giacomocavalieri", repo = "prng" }

[dependencies]
gleam_stdlib = ">= 0.45.0 and < 2.0.0"
gleam_yielder = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
